"""
Database Package

SQLite-based persistence layer.
"""

from packages.database.models import (
    DATABASE_URL,
    AgentEvaluation,
    AgentTrace,
    Base,
    EngineeringTask,
    Evidence,
    FailureEvent,
    HarnessApproval,
    Experiment,
    ExperimentRun,
    Gap,
    InterviewQuestion,
    InterviewSession,
    MaturityAssessment,
    Project,
    ProjectFact,
    ProjectVersion,
    RepositorySnapshot,
    VerificationResult,
    async_session,
    engine,
    get_session,
    init_db,
)
from packages.database.repositories import (
    AgentEvaluationRepository,
    AgentTraceRepository,
    AssessmentRepository,
    EvidenceRepository,
    FailureEventRepository,
    HarnessApprovalRepository,
    ExecutionRepository,
    ExperimentRepository,
    ExperimentRunRepository,
    FactRepository,
    GapRepository,
    InterviewRepository,
    ProjectRepository,
    SnapshotRepository,
    TaskRepository,
    VerificationRepository,
    VersionRepository,
)

__all__ = [
    # Models
    "Base",
    "Project",
    "RepositorySnapshot",
    "ProjectFact",
    "MaturityAssessment",
    "Gap",
    "EngineeringTask",
    "ExecutionRun",
    "VerificationResult",
    "Evidence",
    "ProjectVersion",
    "AgentTrace",
    "AgentEvaluation",
    "HarnessApproval",
    "FailureEvent",
    "InterviewSession",
    "InterviewQuestion",
    # Initialization
    "init_db",
    "get_session",
    "engine",
    "async_session",
    "DATABASE_URL",
    # Repositories
    "ProjectRepository",
    "AgentTraceRepository",
    "AgentEvaluationRepository",
    "HarnessApprovalRepository",
    "FailureEventRepository",
    "SnapshotRepository",
    "FactRepository",
    "AssessmentRepository",
    "GapRepository",
    "TaskRepository",
    "ExecutionRepository",
    "VerificationRepository",
    "EvidenceRepository",
    "VersionRepository",
    "InterviewRepository",
]
